# Generated by Django 2.2.24 on 2021-11-29 23:43

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watrustee', '0010_auto_20211130_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatoruser',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Identity/role of the key guardian'),
        ),
        migrations.AlterField(
            model_name='authenticatoruser',
            name='username',
            field=models.CharField(default=3, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
